version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"

# FIXME uncomment below
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build: ./front
    ports:
      - "4200:4200"
    depends_on:
      - api
